# Generated by Django 5.1.2 on 2024-10-29 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Car Categories',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('passengers', models.IntegerField()),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Extra price per kilometer', max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='cars/')),
                ('features', models.TextField(blank=True, help_text='Enter car features, one per line')),
                ('terms_conditions', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(help_text='Enter WhatsApp number with country code (e.g., 917890123456)', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='RideApp.carcategory')),
            ],
            options={
                'ordering': ['title', 'model'],
            },
        ),
    ]
